on:
  pull_request:
    paths:
      - .github/workflows/pr.yml
      - src/**/*
      - test/**/*
      - playwright.config.ts
      - package.json
      - package-lock.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Restore deps and test
        run: |
          npm ci
          npm test
