name: Github Pages Publish

on:
    push:
        branches:
            - master

concurrency: ci-${{ github.ref }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: sterlingwes/gh-pages-deploy-action@v1.1
              with:
                  access-token: ${{ secrets.GITHUB_TOKEN }}
                  source-directory: public
                  build-command: yarn build
