name: Github Pages Publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

concurrency: ci-${{ github.ref }}

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Restore deps and test
        run: |
          npm ci
          npm test

      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.GH_PAT }}
          source-directory: docs
          deploy-branch: release
          build-command: npm run build
